
histogramme: histogramme_audio.c histogramme_audio.h tst_indexation_audio.c
	gcc -c histogramme_audio.c
	gcc -c tst_indexation_audio.c
	gcc -o histog.out histogramme_audio.o tst_indexation_audio.o 
	./histog.out


clean : 
	rm -f prog *.o 
	rm -f prog *.out
