/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_pfr_JNI_JNI */

#ifndef _Included_com_example_pfr_JNI_JNI
#define _Included_com_example_pfr_JNI_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_pfr_JNI_JNI
 * Method:    majAppli
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_pfr_JNI_JNI_majAppli
  (JNIEnv *, jobject);

/*
 * Class:     com_example_pfr_JNI_JNI
 * Method:    valeurConfiguration
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_pfr_JNI_JNI_valeurConfiguration
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_pfr_JNI_JNI
 * Method:    rechercheImageParCritere
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_pfr_JNI_JNI_rechercheImageParCritere
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_pfr_JNI_JNI
 * Method:    rechercheImageParComp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_pfr_JNI_JNI_rechercheImageParComp
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_pfr_JNI_JNI
 * Method:    rechercheAudioParComp
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_pfr_JNI_JNI_rechercheAudioParComp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_pfr_JNI_JNI
 * Method:    modifierParam
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_pfr_JNI_JNI_modifierParam
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_pfr_JNI_JNI
 * Method:    afficherConfig
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_pfr_JNI_JNI_afficherConfig
  (JNIEnv *, jobject);

/*
 * Class:     com_example_pfr_JNI_JNI
 * Method:    ouvertureFichier
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_pfr_JNI_JNI_ouvertureFichier
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_pfr_JNI_JNI
 * Method:    rechercheTexteParCritere
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_pfr_JNI_JNI_rechercheTexteParCritere
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
