rechercheAudio : rechercheAudio.h rechercheAudio.c arbre.h arbre.c 
				gcc -c -g arbre.c
				gcc -c -g rechercheAudio.c
				gcc -c -g tst_rechercheAudio.c
				gcc -o rechercheAudio.out  arbre.o rechercheAudio.o tst_rechercheAudio.o
				./rechercheAudio.out
				
				
clean :
	rm -f prog *.o
	rm -f prog *.out
