


interface: interface_globale.c interface_globale.h test_interface.c
	gcc -g -c interface_globale.c
	gcc -g -c test_interface.c
	gcc -o interface.out interface_globale.o test_interface.o 
	./interface.out

clean :
	rm -f prog *.o
	rm -f prog *.out
